ARG BASE_IMAGE=python:3.12-slim

FROM ${BASE_IMAGE} AS build

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

COPY . .

RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements/core.txt -r requirements/dev.txt --no-compile --no-cache-dir --root=/build

FROM ${BASE_IMAGE}
WORKDIR /app
COPY --from=build /build/* /usr/
COPY --from=build /app .

ENTRYPOINT [ "/app/start.sh" ]
