# Generated by Django 5.2.7 on 2025-10-30 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='id_ride',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rides.ride'
            ),
        ),
    ]
